# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm
    mappings:
        illustration_images:
            uri_prefix: /illustrations/uploads
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
