<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitadc914a6e6c71bb686f7ca01a1709093
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Symfony\\Runtime\\Symfony\\Component\\' => 34,
            'Symfony\\Component\\Runtime\\' => 26,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Symfony\\Runtime\\Symfony\\Component\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/runtime/Internal',
        ),
        'Symfony\\Component\\Runtime\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/runtime',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitadc914a6e6c71bb686f7ca01a1709093::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitadc914a6e6c71bb686f7ca01a1709093::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitadc914a6e6c71bb686f7ca01a1709093::$classMap;

        }, null, ClassLoader::class);
    }
}
